//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharAcc
    {
        public int CharId { get; set; }
        public string CharName { get; set; }
        public Nullable<bool> IsAlive { get; set; }
        public string IsGM { get; set; }
        public int CampID { get; set; }
        public string AccId { get; set; }
        public Nullable<bool> Removed { get; set; }
    }
}
