//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModTable
    {
        public int ModId { get; set; }
        public string UserId { get; set; }
        public System.DateTime PostedTime { get; set; }
        public int CampID { get; set; }
        public string Content { get; set; }
        public string Sig { get; set; }
        public string Heading { get; set; }
    }
}
