//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryAcc
    {
        public string CharName { get; set; }
        public int CharId { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> CampID { get; set; }
    }
}
