//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransId { get; set; }
        public int SendId { get; set; }
        public int RecId { get; set; }
        public int Amount { get; set; }
        public string Reason { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> TransTime { get; set; }
    }
}
